### ISSUE TITLE
UVR usage

### ISSUE THREAD

**Issue by tenguzame** [demonixis/Unity-toolbox#1]
Dear all,
I'm trying to use the UVR system to test a sample app on my gyroscope-less Lumia 550. How should I set everything up? I see two prefabs in the folder.
Best regards

Michael

**Comment by demonixis** [comment]
Hi,

Unfortunatly the Lumia 550 is not the best phone to do VR, it's very very laggy.. 
The code to do that is no more supported (legacy folder) but you can try one of the two prefab (one is fixed, the ohter can be moved). Please don't hesitate to report me a broken prefab.

The code used to emulate the rotation uses the `OrientationSensor` of the Windows 10 SDK. It tries to return a rotation, but as I said, it's very laggy.

**Comment by tenguzame** [comment]
Thanks for the information! Sadly, the program keeps throwing a Null.Reference error, which seems to be caused by the UVR Controller script. How should I fix it?

**Comment by demonixis** [comment]
I'll take a look at that tomorrow 😉

**Comment by demonixis** [comment]
Hi, I just fixed your issue, thank you for reporting me that problem.
You can try the prefab you want. You can simulate the head tracking using your mouse and by pressing the right button (you can change that behaviour, look at the script `UVRManager`.

**Comment by tenguzame** [comment]
Thank you for this update. It now successfully builds, even though I only see the "Walk" word on the screen. I might be doing some mistake in setting everything up.

**Comment by demonixis** [comment]
I'm afraid that your phone is not compatible with those sources... Or maybe you've to try to debug them using Visual Studio and the Windows 10 SDK.
